import pandas as pd
df=pd.read_csv("retail_sales_data_dirty.csv")
df.info()
df.drop('Sales_Rep',axis=1,inplace=True)
df=df.dropna(subset=(['Region','Price','Revenue']))
df.info()
df = df.copy()  # Optional: to avoid SettingWithCopyWarning
df['Region']=df['Region'].astype("string")
df['Region']=df['Region'].str.replace('N. America','North America')
df['Region']=df['Region'].str.replace('NorthAmerica','North America')
df['Region']=df['Region'].str.replace('NA','North America')
df['Product'] = df['Product'].str.strip()
df['Region'] = df['Region'].str.title() #capitalize each word.
df.drop_duplicates(inplace=True)
df.info()
df
df.rename(columns={"Cost":"Selling Price","Price":"Cost Price"},inplace=True)
df = df.copy()  # Optional: to avoid SettingWithCopyWarning
df['Profit'] =  df['Selling Price'] - df['Cost Price'] 
df['Profit'] = df['Profit'].round(2)
df['Profit_Margin'] = ((df['Profit'] / df['Revenue']) * 100).round(2)
df.info()
df['Product']=df['Product'].astype("string")
df['Category']=df['Category'].astype("string")
df['Date'] = pd.to_datetime(df['Date'])
df.info()
df.to_csv('retail sales clean dataset.csv', index=False)
df
import pandas as pd
df = pd.read_csv('retail sales clean dataset.csv')

import matplotlib.pyplot as plt
product_revenue = df.groupby('Product')['Revenue'].sum()
plt.bar(product_revenue.index, product_revenue.values, color='brown', edgecolor='black')
plt.title('Total Revenue by Product')
plt.xlabel('Product')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.ticklabel_format(style='plain', axis='y') # Ensure that y-axis shows plain numbers (no scientific notation)
plt.show()
import matplotlib.pyplot as plt
product_sales = df.groupby('Product')['Units_Sold'].sum()
plt.pie(product_sales.values, labels=product_sales.index, autopct='%1.1f%%', startangle=90, colors=['lightblue', 'lightgreen', 'lightcoral', 'lightskyblue'])
plt.title('Top-selling Product')
plt.show()
import matplotlib.pyplot as plt
average_profit = df.groupby('Region')['Profit_Margin'].mean().sort_values(ascending=True)
plt.bar(average_profit.index, average_profit.values, color='salmon')
plt.title('Average Profit Margin by Region')
plt.ylabel('Profit Margin (%)')
plt.xlabel('Region')
plt.xticks(rotation=45)
plt.show()
total_profit=df.groupby('Category')['Profit'].sum()
plt.bar(total_profit.index,total_profit.values,color='orange',edgecolor='green')
plt.title('Total Profit by Category')
plt.ylabel('Total Profit')
plt.xticks(rotation=0)
plt.ticklabel_format(style='plain', axis='y')
plt.tight_layout()
plt.show()
plt.scatter(df['Revenue'], df['Profit'], alpha=0.7, color='purple')
plt.title('Revenue vs Profit')
plt.xlabel('Revenue')
plt.ylabel('Profit')
plt.grid(True)
plt.tight_layout()
plt.show()
average_cost=df.groupby('Product')['Cost Price'].mean()
plt.bar(average_cost.index,average_cost.values,color='steelblue',edgecolor='black')
plt.title('Average Cost Price by Product')
plt.ylabel('Average Cost Price')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--')
plt.tight_layout()
plt.show()
plt.scatter(df['Cost Price'], df['Selling Price'], c='green', alpha=0.6)
plt.title('Cost Price vs Selling Price')
plt.xlabel('Cost Price')
plt.ylabel('Selling Price')
plt.grid(True)
plt.tight_layout()
plt.show()
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('retail sales clean dataset.csv')
df['Date'] = pd.to_datetime(df['Date'])
plt.plot(df['Date'], df['Profit'], marker='^', linestyle='-', color='purple')
plt.title('Profit Over Time')
plt.xlabel('Date')
plt.ylabel('Profit')
plt.grid(True)
plt.xticks(rotation=45)  
plt.tight_layout()
plt.show()
